### ISSUE TITLE
Maximum devices for CC2530+CC2591

### ISSUE THREAD

**Issue by oskarn97** [kirovilya/files#1]
Hey!
For the CC2530ZNP-Test_for_CC2591.hex Firmware - what is the number of maximum devices allowed?
Could you please increase it to the maximum that is possible?
Thanks!

**Comment by kirovilya** [comment]
It is your build :) Remember, I ask you ? :))
I do not known how many devices it was.

I can make new build in next week

**Comment by oskarn97** [comment]
Are you sure? I think I only provided one for CC2531

**Comment by kirovilya** [comment]
Yes :) I wrote to you by email :)) you send me file

**Comment by kirovilya** [comment]
Or not to you... :)

**Comment by kirovilya** [comment]
Sorry, it was Jack Wu... I wrote to him too, but before you... he answered later and build this firmware to me... So, sorry.
![screenshot_2018-06-29-21-48-43](https://user-images.githubusercontent.com/8360230/42109482-744df2e0-7be6-11e8-9c10-7313efdeb188.png)

I try to build firmware next week

**Comment by kirovilya** [comment]
I think it was your answer :)

**Comment by kirovilya** [comment]
Hello.
I successful to compile cc2530+cc2591 firmware with NWK_MAX_DEVICE_LIST=28 it is maximum.
When I am increase number - I get error like this (with 29 devices):
![compile_error](https://user-images.githubusercontent.com/8360230/42180419-dfac35dc-7e3f-11e8-913f-b11ef8049843.PNG)
So, last firmware parameters is:
```
ASSERT_RESET
FAKE_CRC_SHDW
TC_LINKKEY_JOIN
SECURE=1
INTER_PAN
HAL_PA_LNA
NWK_MAX_DEVICE_LIST=28
```
[CC2530_CC2590ZNP-Prod.zip](https://github.com/kirovilya/files/files/2156496/CC2530_CC2590ZNP-Prod.zip)

It works but sometimes strange... May be need play with MAXMEMHEAP... I do not known.
I will stay on default parameters.

**Comment by oskarn97** [comment]
I did a firmware with 60 devices and decreased the MAXMEMHEAP to something around 1200. Works fine - thanks

**Comment by kirovilya** [comment]
O!!! What other config parameters?

**Comment by oskarn97** [comment]
TC_LINKKEY_JOIN
HAL_PA_LNA

were the only two I've added consciously. Did not know of the other parameters and seems to be working fine without them. Are they required?

**Comment by kirovilya** [comment]
:) I do not know. I get it from here https://github.com/kirovilya/Z-Stack-firmware/tree/master/coordinator/CC2531
